import os
import re
import logging
import yaml
import json
import functools
import importlib
from types import ModuleType
from typing import Optional, List, Any
from datetime import datetime


from utils.generate_checklist import generate_checklist


logger = logging.getLogger(__name__)



def find_resume_yaml(
    output_dir: str,
    filename_prefix: str,
    min_timestamp: Optional[datetime] = None,
    extra_prefixes: Optional[List[str]] = None,
) -> Optional[str]:
    """
    Find a historical result YAML in output_dir that can be used for resuming.

    Rules:
    - File name starts with filename_prefix (or any prefix in extra_prefixes) and ends with .yaml
    - Exclude *_score.yaml
    - Parse timestamp from file name (format: YYYY-MM-DD_HH-MM-SS)
    - If min_timestamp is provided, result files with timestamps older than this time will be skipped.
    - If multiple candidates exist, pick the newest by timestamp across all allowed prefixes.
    
    Args:
        output_dir: Directory to search.
        filename_prefix: Primary file-name prefix (usually the current model's prefix).
        min_timestamp: Optional minimum timestamp filter.
        extra_prefixes: Additional file-name prefixes that are also acceptable as
            resume sources. Typical use: allow a model to resume from alias models
            that are known to refer to the same underlying judge model
            (e.g. ``GPT-5-Mini_`` and ``api_azure_openai_gpt-5-mini_``).
    """
    if not output_dir or not os.path.isdir(output_dir):
        return None

    # Build the full list of acceptable prefixes. The primary one is always first,
    # so that in case of tie (identical timestamp) it wins deterministically.
    allowed_prefixes: List[str] = [filename_prefix]
    if extra_prefixes:
        for p in extra_prefixes:
            if p and p not in allowed_prefixes:
                allowed_prefixes.append(p)

    candidates: List[tuple[str, datetime]] = []  # (file_path, parsed_timestamp)
    timestamp_pattern = re.compile(r'(\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})')
    
    try:
        for name in os.listdir(output_dir):
            if not any(name.startswith(p) for p in allowed_prefixes):
                continue
            if not name.endswith(".yaml"):
                continue
            if name.endswith("_score.yaml"):
                continue
            
            file_path = os.path.join(output_dir, name)
            
            # Extract timestamp from file name.
            match = timestamp_pattern.search(name)
            if not match:
                continue  # No timestamp in file name -> skip.
            
            try:
                timestamp_str = match.group(1)
                file_timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d_%H-%M-%S")
            except Exception:
                # If timestamp cannot be parsed, skip this file.
                continue
            
            # If min_timestamp is provided, only keep files after it.
            if min_timestamp is not None:
                if file_timestamp < min_timestamp:
                    continue  # Skip files before the timestamp.
            
            candidates.append((file_path, file_timestamp))
    except Exception:
        return None

    if not candidates:
        return None

    # Sort by timestamp in file name (newest first).
    candidates.sort(key=lambda x: x[1], reverse=True)
    return candidates[0][0]


def load_judge_prompt(prompt_path: str, common_judge_prompt_path: str, slides_path: str):
    """
    Load a single case's judge prompt / checklist (JSON) and build the final checklist.
    
    Design goals:
    - A case's `generation_task/judge_prompt.json` should not need to import any Python;
      evaluation code provides a domain-level `common_judge_prompt.json` and merges it with a
      "case overrides domain" strategy.
    - Support callables/partials stored in JSON using a stable representation (generated by migration scripts):
      - {"__type__":"partial","func":"pkg.mod.fn","args":[...],"keywords":{...}}
      - {"__type__":"callable","callable":"pkg.mod.fn"}
    - Always assemble prefixing + page-count truncation via utils.generate_checklist.generate_checklist.
    """
    if not prompt_path or not os.path.exists(prompt_path):
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
    if not prompt_path.endswith(".json"):
        raise ValueError(f"Only JSON judge prompts are supported: {prompt_path}")
    if not common_judge_prompt_path or not os.path.exists(common_judge_prompt_path):
        raise FileNotFoundError(f"Common judge prompt file not found: {common_judge_prompt_path}")
    if not common_judge_prompt_path.endswith(".json"):
        raise ValueError(f"Only JSON common judge prompts are supported: {common_judge_prompt_path}")

    def _load_json(path: str) -> dict[str, Any]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            raise ValueError(f"judge prompt json must be an object: {path}")
        return data

    def _import_from_qualname(qualname: str):
        """
        Import callable by fully-qualified name like 'utils.count_pages.check_slide_count'.
        """
        if not qualname or "." not in qualname:
            raise ValueError(f"Invalid qualname: {qualname!r}")
        mod_name, attr = qualname.rsplit(".", 1)
        mod: ModuleType = importlib.import_module(mod_name)
        fn = getattr(mod, attr)
        if not callable(fn):
            raise TypeError(f"Imported object is not callable: {qualname}")
        return fn

    def _stub_callable(err_msg: str):
        def _f(_slides_path: str):
            return {
                "answer": "no",
                "explanation": f"[judged by code] {err_msg}",
                "log": err_msg,
            }
        return _f

    def _decode_obj(x: Any) -> Any:
        if isinstance(x, list):
            return [_decode_obj(v) for v in x]
        if isinstance(x, dict):
            t = x.get("__type__")
            if t == "partial":
                try:
                    fn = _import_from_qualname(str(x.get("func") or ""))
                    args = _decode_obj(x.get("args") or [])
                    kwargs = _decode_obj(x.get("keywords") or {})
                    if not isinstance(args, list):
                        raise TypeError("partial.args must be a list")
                    if not isinstance(kwargs, dict):
                        raise TypeError("partial.keywords must be an object")
                    return functools.partial(fn, *args, **kwargs)
                except Exception as e:
                    msg = f"Failed to decode partial {x}: {e}"
                    logger.warning(msg)
                    return _stub_callable(msg)
            if t == "callable":
                try:
                    return _import_from_qualname(str(x.get("callable") or ""))
                except Exception as e:
                    msg = f"Failed to decode callable {x}: {e}"
                    logger.warning(msg)
                    return _stub_callable(msg)
            # Plain dict: recursively decode values.
            return {k: _decode_obj(v) for k, v in x.items()}
        return x

    def _get_merged(key: str, case_json: dict[str, Any], common_json: dict[str, Any]) -> Any:
        """
        Only the new material_* key naming is supported.
        Merge strategy: case overrides common (if key is absent in case, fall back to common).
        """
        if key in case_json:
            return case_json[key]
        if key in common_json:
            return common_json[key]
        return None

    case_json = _load_json(prompt_path)
    common_json = _load_json(common_judge_prompt_path)

    si_prefix = _decode_obj(_get_merged("material_independent_prefix", case_json, common_json))
    sd_prefix = _decode_obj(_get_merged("material_dependent_prefix", case_json, common_json))

    si_1 = _decode_obj(_get_merged("material_independent_checklist_1", case_json, common_json))
    si_2 = _decode_obj(_get_merged("material_independent_checklist_2", case_json, common_json))
    sd_1 = _decode_obj(_get_merged("material_dependent_checklist_1", case_json, common_json))
    sd_2 = _decode_obj(_get_merged("material_dependent_checklist_2", case_json, common_json))
    sd_3 = _decode_obj(_get_merged("material_dependent_checklist_3", case_json, common_json))

    required = {
        "material_independent_checklist_1": si_1,
        "material_independent_checklist_2": si_2,
        "material_dependent_checklist_1": sd_1,
        "material_dependent_checklist_2": sd_2,
        "material_dependent_checklist_3": sd_3,
    }
    missing = [k for k, v in required.items() if v is None]
    if missing:
        raise KeyError(
            "Missing required keys in judge prompt json (case/common merge): "
            + ", ".join(missing)
        )

    # Ensure checklists are lists (avoid None causing add_prefix to crash later).
    if not all(isinstance(lst, list) for lst in [si_1, si_2, sd_1, sd_2, sd_3]):
        raise TypeError(f"The checklist(s) are not list type: {prompt_path}, {common_judge_prompt_path}.")

    return generate_checklist(
        slides_path,
        material_independent_checklist=[si_1, si_2],
        material_dependent_checklist=[sd_1, sd_2, sd_3],
        material_independent_prefix=si_prefix,
        material_dependent_prefix=sd_prefix,
    )


def load_existing_results(resume_yaml_path: str) -> Optional[dict]:
    """Load a historical result YAML; return None on failure (does not affect main flow)."""
    if not resume_yaml_path or not os.path.exists(resume_yaml_path):
        return None
    try:
        with open(resume_yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return data if isinstance(data, dict) else None
    except Exception as e:
        logger.warning(f"Failed to load resume YAML {resume_yaml_path}: {e}")
        return None


def is_result_complete(checklist: List[List[Any]], existing_result: Optional[dict]) -> bool:
    """
    Check whether existing results are complete (all checklist items exist and answer is not None).
    
    Args:
        checklist: Checklist items.
        existing_result: Existing result dict.
    
    Returns:
        True if results are complete, False otherwise.
    """
    if not existing_result or not isinstance(existing_result, dict):
        return False
    
    # Iterate over all checklist items and ensure each has a complete result.
    for i, sublist in enumerate(checklist):
        outer_key = f"{i+1}"
        if outer_key not in existing_result:
            return False
        
        inner_dict = existing_result[outer_key]
        if not isinstance(inner_dict, dict):
            return False
        
        for j, _ in enumerate(sublist):
            inner_key = f"{i+1}.{j+1}"
            if inner_key not in inner_dict:
                return False
            
            item_result = inner_dict[inner_key]
            if not isinstance(item_result, dict):
                return False
            
            # Ensure answer exists and is not None.
            if item_result.get("answer") is None:
                return False
    
    return True